const dataCandidatos = [
    {id: "1",
    nombre: "Kif",
    apellido: "Kroker",
    edad: "28",
    linkCV: "linkedin.com/Kif",
    skills: "Liderazgo, Teamwork, Adaptabilidad.",
    fulltime: "Si",
    movilidad: "Si",
    img: "./img/candidatos/alien1.jpg",
    puesto: "Cocinero"
    },
    {id: "2",
    nombre: "Morbo",
    apellido: "Vorian",
    edad: "22",
    linkCV: "linkedin.com/Morbo",
    skills: "Creativo, Honesto, Responsable.",
    fulltime: "No",
    movilidad: "No",
    img: "./img/candidatos/alien2.jpg",
    puesto: "Periodista"
    },
    {id: "3",
    nombre: "Edna",
    apellido: "Inara",
    edad: "32",
    linkCV: "linkedin.com/Edna",
    skills: "Liderazgo, Adaptabilidad, Empatía.",
    fulltime: "Si",
    movilidad: "No",
    img: "./img/candidatos/alien3.jpg",
    puesto: "Abogada"
    },
    {id: "4",
    nombre: "Armando",
    apellido: "Barreda",
    edad: "27",
    linkCV: "linkedin.com/Armando",
    skills: "Teamwork, Iniciativa, Ética Laboral.",
    fulltime: "No",
    movilidad: "Si",
    img: "./img/candidatos/foto1.jpg",
    puesto: "Mecánico"
    },
    {id: "5",
    nombre: "Javier",
    apellido: "Alonso",
    edad: "35",
    linkCV: "linkedin.com/Javier",
    skills: "Integridad, Productividad, Conocimiento Tecnológico.",
    fulltime: "No",
    movilidad: "No",
    img: "./img/candidatos/foto2.jpg",
    puesto: "Programador"
    },
    {id: "6",
    nombre: "Hermes",
    apellido: "Conrad",
    edad: "41",
    linkCV: "linkedin.com/Hermes_Conrad",
    skills: "Bailarín Olímpico, Productividad, Archivador Compulsivo.",
    fulltime: "Si",
    movilidad: "No",
    img: "./img/candidatos/hermes.jpg",
    puesto: "Inspector"
    },
    {id: "7",
    nombre: "Scruffy",
    apellido: "Scruffington",
    edad: "55",
    linkCV: "linkedin.com/Scruffy",
    skills: "Lealtad, Tranquilidad, Fiable.",
    fulltime: "Si",
    movilidad: "No",
    img: "./img/candidatos/scruffy.jpg",
    puesto: "Conserje"
    },
    {id: "8",
    nombre: "Zapp",
    apellido: "Brannigan",
    edad: "27",
    linkCV: "linkedin.com/Javier",
    skills: "Sexlexia, Escritor, Manejo de RRHH.",
    fulltime: "Si",
    movilidad: "Si",
    img: "./img/candidatos/Zapp_Brannigan.png",
    puesto: "Piloto"
    },
    {id: "9",
    nombre: "Mordelón",
    apellido: "Nibbler",
    edad: "85",
    linkCV: "linkedin.com/Mordelon",
    skills: "Creador de Materia Oscura, Guardián, Secretismo.",
    fulltime: "Si",
    movilidad: "No",
    img: "./img/candidatos/foto11.jpg",
    puesto: "Embajador"
    },
    {id: "10",
    nombre: "Lars",
    apellido: "Fillmore",
    edad: "45",
    linkCV: "linkedin.com/Lars_Fillmore",
    skills: "Integridad, Productividad, Conocimiento Tecnológico.",
    fulltime: "No",
    movilidad: "No",
    img: "./img/candidatos/Lars_Fillmore.png",
    puesto: "Programador"
    },
    {id: "11",
    nombre: "Morgan",
    apellido: "Proctor",
    edad: "53",
    linkCV: "linkedin.com/Morgan_Proctor",
    skills: "Respeto, Rigurosa, Conocimiento Burocrático.",
    fulltime: "Si",
    movilidad: "Si",
    img: "./img/candidatos/morgan_proctor.png",
    puesto: "Burócrata"
    },
    {id: "12",
    nombre: "Philip J.",
    apellido: "Fry",
    edad: "25",
    linkCV: "linkedin.com/Fry",
    skills: "Optimismo, Conocimiento Histórico del Siglo XXI.",
    fulltime: "No",
    movilidad: "Si",
    img: "./img/candidatos/fry.jpg",
    puesto: "Repartidor"
    },
    {id: "13",
    nombre: "Javier",
    apellido: "Alonso",
    edad: "75",
    linkCV: "linkedin.com/Javier",
    skills: "Integridad, Productividad, Conocimiento Tecnológico.",
    fulltime: "No",
    movilidad: "No",
    img: "./img/candidatos/robot.jpg",
    puesto: "Programador"
    },
    {id: "14",
    nombre: "Mutante",
    apellido: "Atómico",
    edad: "27",
    linkCV: "linkedin.com/Mutante",
    skills: "Fuerza, Capacidad de recoger varias cosas a la vez.",
    fulltime: "Si",
    movilidad: "No",
    img: "./img/candidatos/5_brazos.jpg",
    puesto: "Malabarista"
    },
    {id: "15",
    nombre: "Ronald",
    apellido: "Reagan",
    edad: "93",
    linkCV: "linkedin.com/Mister_president",
    skills: "Actor, Estadista, Optimista.",
    fulltime: "No",
    movilidad: "No",
    img: "./img/candidatos/ronald.jpg",
    puesto: "Programador"
    },
    {id: "16",
    nombre: "Gusano",
    apellido: "Catador",
    edad: "58",
    linkCV: "linkedin.com/Slurm_Worm",
    skills: "Papilas Gustativas, Productividad, Foodie.",
    fulltime: "No",
    movilidad: "No",
    img: "./img/candidatos/catador_slurm.jpg",
    puesto: "Catador"
    },
    {id: "17",
    nombre: "Lucy",
    apellido: "Liubot",
    edad: "30",
    linkCV: "linkedin.com/Lucy_Liubot",
    skills: "Actriz, Fuerza, Energía Ilimitada.",
    fulltime: "Si",
    movilidad: "No",
    img: "./img/candidatos/lucy.jpg",
    puesto: "Actriz"
    },
    {id: "18",
    nombre: "Labarbara",
    apellido: "Conrad",
    edad: "35",
    linkCV: "linkedin.com/Labarbara",
    skills: "Bondadosa, Productividad, Fitness.",
    fulltime: "Si",
    movilidad: "No",
    img: "./img/candidatos/foto2.jpg",
    puesto: "Niñera"
    },
    {id: "19",
    nombre: "Billy",
    apellido: "West",
    edad: "56",
    linkCV: "linkedin.com/Billy",
    skills: "Trabajo de la tierra, Químicos, Reparación de Robots.",
    fulltime: "Si",
    movilidad: "No",
    img: "./img/candidatos/granjero.jpg",
    puesto: "Granjero Hidrofónico"
    },
    {id: "20",
    nombre: "Diablo",
    apellido: "Robot",
    edad: "99",
    linkCV: "linkedin.com/Diablo",
    skills: "Maldad, Torturas, Generar Dolor.",
    fulltime: "Si",
    movilidad: "Si",
    img: "./img/candidatos/diablo.jpg",
    puesto: "Torturador"
    }
];

export default dataCandidatos;